### ISSUE TITLE
gitsign fails to build with cosign 3.1.x

### ISSUE THREAD

**Issue by jas4711** [sigstore/gitsign#826]
Hi. I'm upgrading cosign in Debian and ran into a problem for gitsign, it fails like this:

```
# github.com/sigstore/gitsign/internal/commands/attest
src/github.com/sigstore/gitsign/internal/commands/attest/attest.go:78:36: undefined: signcommon.GetSignerVerifier
```

See full build log here: https://salsa.debian.org/jas/cosign/-/jobs/9753241#L5017

I thought this was a cosign API bug but they don't consider so: https://github.com/sigstore/cosign/issues/4923

Could you make gitsign work with latest cosign?

Thanks!

**Comment by arpitjain099** [comment]
Looked into this. The break is that cosign v3.1.0 removed `signcommon.GetSignerVerifier` and made the SignerVerifier builders (`signerFromKeyOpts`/`signerFromNewKey`) unexported. The exported entry point is now `GetKeypairAndToken`, which returns a `sign.Keypair` rather than a `*signcommon.SignerVerifier` - and gitsign's attest path needs the latter (it does `dssesig.WrapSigner(sv)` and reads `sv.Cert` in `internal/attest`), so a straight version bump can't work.

Two ways forward:

1. Minimal/pragmatic: reconstruct the ephemeral-Fulcio SignerVerifier in gitsign from the still-exported pieces - `cosign.GeneratePrivateKeyWithAlgorithm` + `signature.LoadSignerVerifierFromAlgorithmDetails` for the ephemeral key, then `fulcio.NewSigner(ctx, ko, signer)` for the cert. Smallest diff, restores current behavior, unblocks the build (and the Debian packaging @jas4711 hit).
2. Fuller: move the attestor onto cosign's new keypair flow (or sigstore-go), which aligns with where #763 is heading.

Happy to send a PR for option 1 to get the build green again if that's acceptable, or help with option 2 if you'd rather take the migration route. Which would you prefer?

**Comment by ogulcanaydogan** [comment]
I looked into this. The break comes from sigstore/cosign#4618 ("Sign exclusively via sigstore-go"), which reworked the signing path. `GetSignerVerifier` was effectively replaced by the now-unexported `signerFromKeyOpts` in `cmd/cosign/cli/signcommon`, so it is no longer importable.

gitsign's attestor (`internal/attest`) only needs two things off the value: a `signature.SignerVerifier` to DSSE-sign the payload, and the `.Cert` bytes for the Rekor upload. The `signcommon.SignerVerifier` struct itself is still exported and constructable (the existing tests build one directly), so the gap is purely the keyless constructor.

Two ways forward:
1. Ask cosign to export a small helper again (e.g. a public `GetSignerVerifier` wrapping `signerFromKeyOpts`), then gitsign just bumps the dep and updates the one call site.
2. Keep gitsign self-contained: build the ephemeral keyless `signature.SignerVerifier` + cert here using the new `signcommon.GetKeypairAndToken` flow, and drop the dependency on the removed constructor.

Given cosign explicitly offers no API stability guarantees, (2) is probably the more durable choice even though it's a bit more code. I'm happy to take this on — do the maintainers have a preference between re-exporting in cosign vs adapting gitsign?

**Comment by arpitjain099** [comment]
Thanks @ogulcanaydogan, that lines up with what I'd dug into. I went ahead and put up #828 with the minimal fix to get the build green again: `fulcio.NewSigner` and the `SignerVerifier` struct are both still exported, so the attest path can rebuild the keyless signer the way `GetSignerVerifier` used to without touching the attestor. If the maintainers would rather move onto the new `GetKeypairAndToken`/sigstore-go keypair flow, that's a good follow-up.
